### PR TITLE
Patch per rwjblue's requests

### PR DESCRIPTION
**Pull request by acorncom**
I'm not positive I got the `this` nomenclature accurate, so you should probably double-check me on that :-)

### CODE REVIEW

**Comment by cibernox** [comment]
Sorry, I missed this PR for a long time. My mailbox is overflooded lately. I'll update the PR and rebase if necessary.

**Comment by acorncom** [comment]
@cibernox No problem, we're all busy :-)

**Comment by michaelrkn** [comment]
Hey @cibernox - any chance you can get your PR updated this weekend so we can get https://github.com/ember-cli/ember-cli/pull/4218 merged? Thanks in advance!

**Comment by cibernox** [comment]
@michaelrkn Actually I updated the PR right away but coverall was sad because code coverage reduced by 0.01 or something like that. 

I will check to see if I can see why.

**Comment by michaelrkn** [comment]
Oh I just assumed it hadn't been updated because of the failing checks - it looks like the AppVeyor build also failed.

**Pull request merged**
